DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE Librarian CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE BOOK_STATUS CASCADE CONSTRAINTS;
DROP TABLE BORROWING CASCADE CONSTRAINTS;
DROP TABLE FINE CASCADE CONSTRAINTS;
DROP TABLE TRANSACTIONS CASCADE CONSTRAINTS;
DROP TABLE REPORTS CASCADE CONSTRAINTS;